export const metadata = {
  title: "Terms of Service — Socialyze",
};

export default function TermsOfService() {
  return (
    <main className="max-w-2xl mx-auto px-6 py-14 text-warm-white/70 space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-warm-white mb-2">Terms of Service</h1>
        <p className="text-sm text-warm-white/30">Last updated: June 2025</p>
      </div>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-warm-white">The Service</h2>
        <p className="text-sm leading-relaxed">
          Socialyze provides AI-generated audits of public social media profiles. You submit a handle, we analyze publicly available profile signals and generate a report. Audits are for informational purposes only.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-warm-white">Credits and Payments</h2>
        <p className="text-sm leading-relaxed">
          Audits are purchased as one-time credit packs. Credits are consumed when a full audit is successfully generated. <span className="text-warm-white/90">Used credits are non-refundable.</span> Unused credits do not expire. If an audit fails due to a technical error on our end, the credit will be restored.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-warm-white">Acceptable Use</h2>
        <p className="text-sm leading-relaxed">
          You agree to use Socialyze only for lawful purposes. You may not attempt to reverse-engineer the service, resell audit outputs without attribution, automate requests to abuse the platform, or use it to audit profiles you do not have rights to analyze commercially.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-warm-white">AI Disclaimer</h2>
        <p className="text-sm leading-relaxed">
          Audit content is generated by an AI model (Anthropic Claude). All scores, follower estimates, persona descriptions, and recommendations are AI-generated outputs — not verified facts. Socialyze makes no guarantees about the accuracy of any specific metric. Use the results as a directional guide, not as definitive data.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-warm-white">Limitation of Liability</h2>
        <p className="text-sm leading-relaxed">
          Socialyze is provided &quot;as is&quot; without warranties of any kind. We are not liable for business decisions made based on audit outputs, loss of revenue, or any indirect damages arising from use of the service. Our total liability is limited to the amount you paid in the 30 days preceding the claim.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-warm-white">Changes to These Terms</h2>
        <p className="text-sm leading-relaxed">
          We may update these terms from time to time. Continued use of the service after changes are posted constitutes acceptance of the updated terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="text-lg font-semibold text-warm-white">Contact</h2>
        <p className="text-sm leading-relaxed">
          Questions? Email{" "}
          <a href="mailto:danieladan640@gmail.com" className="text-teal hover:underline">
            danieladan640@gmail.com
          </a>
          .
        </p>
      </section>
    </main>
  );
}
